language: node_js
node_js:
    - "0.10"
    - "0.12"
    - "iojs"

services:
    - elasticsearch

# wait for elasticsearh to start up
before_script:
  - sleep 10

after_success:
    - npm run coveralls

sudo: false
