language: node_js
node_js:
    - "0.10"
    - "0.12"
    - "iojs"

os:
    - linux
    - osx

services:
    - elasticsearch

# wait for elasticsearh to start up
before_script:
  - chmod -w ./test/spool.nowrite
  - sleep 10

after_success:
    - npm run coveralls

sudo: false
