language: node_js
node_js:
    - "4"
    - "6"

os:
    - linux
#   - osx

matrix:
    allow_failures:
        - os: osx
#       - node_js: iojs
    fast_finish: true

services:
    - elasticsearch

# wait for elasticsearch to start up
before_script:
    - chmod -w ./test/spool/nowrite
    - sleep 12

after_success:
    - npm install istanbul codecov
    - NODE_ENV=cov ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha -- -R spec
    - cat ./coverage/coverage.json | ./node_modules/.bin/codecov

sudo: false
